#ifndef MEMORY_OBJECT_H
#define MEMORY_OBJECT_H

#include <machina/memory_object.h>

typedef mcn_memobj_t memory_object_t;
typedef mcn_memobj_ctrl_t memory_object_control_t;
typedef mcn_memobj_name_t  memory_object_name_t;

typedef mcn_memobj_copy_strategy_t memory_object_copy_strategy_t;
#define MEMORY_OBJECT_COPY_NONE MCN_MEMOBJ_COPY_NONE
#define MEMORY_OBJECT_COPY_CALL MCN_MEMOBJ_COPY_CALL
#define MEMORY_OBJECT_COPY_DELAY MCN_MEMOBJ_COPY_DELAY
#define MEMORY_OBJECT_COPY_TEMPORARY MCN_MEMOBJ_COPY_TEMP

typedef mcn_memobj_return_t memory_object_return_t;
#define MEMORY_OBJECT_RETURN_NONE MCN_MEMOBJ_RETURN_NONE
#define MEMORY_OBJECT_RETURN_DIRTY MCN_MEMOBJ_RETURN_DIRTY
#define MEMORY_OBJECT_RETURN_ALL MCN_MEMOBJ_RETURN_ALL

#define MEMORY_OBJECT_NULL MCN_MEMOBJ_NULL

#endif
