#ifndef MACH_MESSAGE_H
#define MACH_MESSAGE_H

#include <machina/message.h>

typedef mcn_msgbits_t mach_msg_bits_t;
typedef mcn_msgsize_t mach_msg_size_t;
typedef mcn_msgid_t mach_msg_id_t;

typedef mcn_msgheader_t mach_msg_header_t;
#define msgh_remote_port msgh_remote
#define msgh_local_port msgh_local

typedef mcn_msgtype_t mach_msg_type_t;
typedef mcn_msgtype_long_t mach_msg_type_long_t;
typedef mcn_msgtype_name_t mach_msg_type_name_t;

typedef unsigned long mach_msg_timeout_t;

#define MACH_MSG_TIMEOUT_NONE ((mach_msg_timeout_t)0)

#define MACH_MSGH_BITS_ZERO		0x00000000
#define MACH_MSGH_BITS_REMOTE_MASK	0x000000ff
#define MACH_MSGH_BITS_LOCAL_MASK	0x0000ff00
#define MACH_MSGH_BITS_COMPLEX		0x80000000U
#define	MACH_MSGH_BITS_CIRCULAR		0x40000000	/* internal use only */
#define	MACH_MSGH_BITS_COMPLEX_PORTS	0x20000000	/* internal use only */
#define	MACH_MSGH_BITS_COMPLEX_DATA	0x10000000	/* internal use only */
#define	MACH_MSGH_BITS_MIGRATED		0x08000000	/* internal use only */
#define	MACH_MSGH_BITS_UNUSED		0x07ff0000

#define MACH_MSG_TYPE_UNSTRUCTURED MCN_MSGTYPE_UNSTRUCTURED
#define MACH_MSG_TYPE_BIT MCN_MSGTYPE_BIT
#define MACH_MSG_TYPE_BOOLEAN MCN_MSGTYPE_BOOLEAN
#define MACH_MSG_TYPE_INTEGER_16 MCN_MSGTYPE_INT16
#define MACH_MSG_TYPE_INTEGER_32 MCN_MSGTYPE_INT32
#define MACH_MSG_TYPE_CHAR MCN_MSGTYPE_CHAR
#define MACH_MSG_TYPE_BYTE MCN_MSGTYPE_BYTE
#define MACH_MSG_TYPE_INTEGER_8 MCN_MSGTYPE_INT8
#define MACH_MSG_TYPE_REAL MCN_MSGTYPE_REAL
#define MACH_MSG_TYPE_STRING MCN_MSGTYPE_STRING
#define MACH_MSG_TYPE_STRING_C MCN_MSGTYPE_CSTRING

#define MACH_MSG_TYPE_MOVE_RECEIVE MCN_MSGTYPE_MOVERECV
#define MACH_MSG_TYPE_MOVE_SEND MCN_MSGTYPE_MOVESEND
#define MACH_MSG_TYPE_MOVE_SEND_ONCE MCN_MSGTYPE_MOVEONCE
#define MACH_MSG_TYPE_COPY_SEND MCN_MSGTYPE_COPYSEND
#define MACH_MSG_TYPE_MAKE_SEND MCN_MSGTYPE_MAKESEND
#define MACH_MSG_TYPE_MAKE_SEND_ONCE MCN_MSGTYPE_MAKEONCE

#define MACH_MSG_TYPE_PORT_NAME MCN_MSGTYPE_PORTNAME
#define MACH_MSG_TYPE_PORT_RECEIVE MCN_MSGTYPE_PORTRECV
#define MACH_MSG_TYPE_PORT_SEND MCN_MSGTYPE_PORTSEND
#define MACH_MSG_TYPE_PORT_SEND_ONCE MCN_MSGTYPE_PORTONCE

#define MACH_MSG_TYPE_LAST MCN_MSGTYPE_LAST

#define MACH_MSG_TYPE_POLYMORPHIC MCN_MSGTYPE_POLYMORPHIC


#define MACH_MSG_TYPE_PORT_ANY(x)			\
  (((x) >= MACH_MSG_TYPE_MOVE_RECEIVE) &&		\
   ((x) <= MACH_MSG_TYPE_MAKE_SEND_ONCE))

#define	MACH_MSG_TYPE_PORT_ANY_SEND(x)			\
  (((x) >= MACH_MSG_TYPE_MOVE_SEND) &&			\
   ((x) <= MACH_MSG_TYPE_MAKE_SEND_ONCE))

#define	MACH_MSG_TYPE_PORT_ANY_RIGHT(x)			\
  (((x) >= MACH_MSG_TYPE_MOVE_RECEIVE) &&		\
   ((x) <= MACH_MSG_TYPE_MOVE_SEND_ONCE))


typedef int mach_msg_option_t;

#define MACH_MSG_OPTION_NONE 	0x0000

#define MACH_SEND_MSG		0x0001
#define MACH_RCV_MSG		0x0002

#define MACH_SEND_TIMEOUT	0x0010
#define MACH_SEND_NOTIFY	0x0020
#define MACH_SEND_INTERRUPT	0x0040
#define MACH_SEND_CANCEL	0x0080
#define MACH_RCV_TIMEOUT	0x0100
#define MACH_RCV_NOTIFY		0x0200
#define MACH_RCV_INTERRUPT	0x0400
#define MACH_RCV_LARGE		0x0800


typedef mcn_msgioret_t mach_msg_return_t;
#define MACH_MSG_SUCCESS MSGIO_SUCCESS
#define MACH_MSG_MASK MSGIO_MSG_MASK
#define MACH_MSG_IPC_SPACE MSGIO_MSG_IPC_SPACE
#define MACH_MSG_VM_SPACE MSGIO_MSG_VM_SPACE
#define MACH_MSG_IPC_KERNEL MSGIO_MSG_IPC_KERNEL
#define MACH_MSG_VM_KERNEL MSGIO_MSG_VM_KERNEL

#define MACH_SEND_INVALID_DATA MSGIO_SEND_INVALID_DATA
#define MACH_SEND_INVALID_DEST MSGIO_SEND_INVALID_DEST
#define MACH_SEND_TIMED_OUT MSGIO_SEND_TIMED_OUT
#define MACH_SEND_WILL_NOTIFY MSGIO_SEND_WILL_NOTIFY
#define MACH_SEND_NOTIFY_IN_PROGRESS MSGIO_SEND_NOTIFY_IN_PROGRESS
#define MACH_SEND_INTERRUPTED MSGIO_SEND_INTERRUPTED
#define MACH_SEND_MSG_TOO_SMALL MSGIO_SEND_TOO_SMALL
#define MACH_SEND_INVALID_REPLY MSGIO_SEND_INVALID_REPLY
#define MACH_SEND_INVALID_RIGHT MSGIO_SEND_INVALID_RIGHT
#define MACH_SEND_INVALID_NOTIFY MSGIO_SEND_INVALID_NOTIFY
#define MACH_SEND_INVALID_MEMORY MSGIO_SEND_INVALID_MEMORY
#define MACH_SEND_NO_BUFFER MSGIO_SEND_NO_BUFFER
#define MACH_SEND_NO_NOTIFY MSGIO_SEND_NO_NOTIFY
#define MACH_SEND_INVALID_TYPE MSGIO_SEND_INVALID_TYPE
#define MACH_SEND_INVALID_HEADER MSGIO_SEND_INVALID_HEADER

#define MACH_RCV_INVALID_NAME MSGIO_RCV_INVALID_NAME
#define MACH_RCV_TIMED_OUT MSGIO_RCV_TIMED_OUT
#define MACH_RCV_TOO_LARGE MSGIO_RCV_TOO_LARGE
#define MACH_RCV_INTERRUPTED MSGIO_RCV_INTERRUPTED
#define MACH_RCV_PORT_CHANGED MSGIO_RCV_PORT_CHANGED
#define MACH_RCV_INVALID_NOTIFY MSGIO_RCV_INVALID_NOTIFY
#define MACH_RCV_INVALID_DATA MSGIO_RCV_INVALID_DATA
#define MACH_RCV_PORT_DIED MSGIO_RCV_PORT_DIED
#define MACH_RCV_IN_SET MSGIO_RCV_IN_SET
#define MACH_RCV_HEADER_HERROR MSGIO_RCV_HEADER_ERROR
#define MACH_RCV_BODY_ERROR MSGIO_RCV_BODY_ERROR

mach_msg_return_t mach_msg(mach_msg_header_t *msg,
			   mach_msg_option_t option,
			   mach_msg_size_t send_size,
			   mach_msg_size_t rcv_size,
			   mach_port_t rcv_name,
			   mach_msg_timeout_t timeout,
			   mach_port_t notify);

#endif
