#ifndef MACH_PORT_H
#define MACH_PORT_H

#include <machina/types.h>

typedef mcn_portid_t mach_port_t;
typedef mcn_portid_array_t mach_port_array;

#define MACH_PORT_NULL MCN_PORTID_NULL
#define MACH_PORT_DEAD MCN_PORTID_DEAD

typedef mcn_portright_t mach_port_right_t;

#define MACH_PORT_RIGHT_SEND MCN_PORTRIGHT_SEND
#define MACH_PORT_RIGHT_RECEIVE MCN_PORTRIGHT_RECV
#define MACH_PORT_RIGHT_SEND_ONCE MCN_PORTRIGHT_ONCE
#define MACH_PORT_RIGHT_PORT_SET MCN_PORTRIGHT_PSET
#define MACH_PORT_RIGHT_DEAD_NAME MCN_PORTRIGHT_DEAD

typedef mcn_porttype_t mach_port_type_t;
#define MACH_PORT_TYPE(_x) MCN_PORTTYPE(_x)
#define MACH_PORT_TYPE_NONE	((mach_port_type_t) 0)
#define MACH_PORT_TYPE_SEND	 MACH_PORT_TYPE(MACH_PORT_RIGHT_SEND)
#define MACH_PORT_TYPE_RECEIVE	 MACH_PORT_TYPE(MACH_PORT_RIGHT_RECEIVE)
#define MACH_PORT_TYPE_SEND_ONCE MACH_PORT_TYPE(MACH_PORT_RIGHT_SEND_ONCE)
#define MACH_PORT_TYPE_PORT_SET  MACH_PORT_TYPE(MACH_PORT_RIGHT_PORT_SET)
#define MACH_PORT_TYPE_DEAD_NAME MACH_PORT_TYPE(MACH_PORT_RIGHT_DEAD_NAME)

#define MACH_PORT_TYPE_SEND_RECEIVE					\
		(MACH_PORT_TYPE_SEND|MACH_PORT_TYPE_RECEIVE)
#define	MACH_PORT_TYPE_SEND_RIGHTS					\
		(MACH_PORT_TYPE_SEND|MACH_PORT_TYPE_SEND_ONCE)
#define	MACH_PORT_TYPE_PORT_RIGHTS					\
		(MACH_PORT_TYPE_SEND_RIGHTS|MACH_PORT_TYPE_RECEIVE)
#define	MACH_PORT_TYPE_PORT_OR_DEAD					\
		(MACH_PORT_TYPE_PORT_RIGHTS|MACH_PORT_TYPE_DEAD_NAME)
#define MACH_PORT_TYPE_ALL_RIGHTS					\
		(MACH_PORT_TYPE_PORT_OR_DEAD|MACH_PORT_TYPE_PORT_SET)

#define MACH_PORT_TYPE_DNREQUEST MCN_PORTTYPE_DNREQUEST
#define MACH_PORT_TYPE_MAREQUEST MCN_PORTTYPE_MAREQUEST

typedef mcn_seqno_t mach_port_seqno_t;
typedef mcn_msgcount_t mach_port_msgcount_t;

#define MACH_PORT_QLIMIT_DEFAULT MCN_QLIMIT_DEFAULT
#define MACH_PORT_QLIMIT_MAX MCN_QLIMIT_MAX

#endif
