name: Project Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Cache toolchain
      id: cache-toolchain
      uses: actions/cache@v3
      with:
        path: toolchain
        key: ${{ runner.os }}-toolchain-${{ hashFiles('toolchain/**') }}
        restore-keys: |
          ${{ runner.os }}-toolchain-

    - name: Download GCC Toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: makefile.yml
        name: cross-toolchains
        repo: glguida/gcc_toolchain_build
        path: toolchain

    - name: Setup environment
      run: |
        echo "${{ github.workspace }}/toolchain/bin" >> $GITHUB_PATH
        chmod +x toolchain/bin/*

    - name: Submodules fetch
      run: |
        git submodule update --init --recursive

    - name: Build AMD64
      run: |
        ./configure ARCH=amd64
        make -j$(nproc)

    - name: Build RISCV64
      run: |
        ./configure ARCH=riscv64
        make -j$(nproc)
