name: Project Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Download GCC Toolchain
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: makefile.yml
        name: cross-toolchains
        repo: glguida/gcc_toolchain_build
        path: toolchain

    - name: Setup environment
      run: |
        echo "${{ github.workspace }}/toolchain/bin" >> $GITHUB_PATH
        chmod +x toolchain/bin/*

    - name: Build AMD64
      run: |
        ./configure ARCH=amd64
        make -j$(nproc)

    - name: Build RISCV64
      run: |
        ./configure ARCH=riscv64
        make -j$(nproc)
